"""
Django settings for mmsserver project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from corsheaders.defaults import default_headers
import dj_database_url
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Helper function to convert environment variable strings to booleans
def env_to_bool(env_var_name, default=False):
    value = os.environ.get(env_var_name)
    if value is None:
        return default
    return value.lower() in ('true', '1', 't', 'yes')

# Helper function to get integer from environment variable
def env_to_int(env_var_name, default=0):
    value = os.environ.get(env_var_name)
    if value is None:
        return default
    try:
        # Attempt to remove trailing commas if present, common in .env files
        return int(value.strip(','))
    except ValueError:
        return default


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

TIME_ZONE = 'Asia/Kuala_Lumpur'
USE_TZ = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')

PRODUCTION_API_URL = os.getenv('PRODUCTION_API_URL', 'http://127.0.0.1:8000/')


#Supabase
SUPABASE_JWT_SECRET = os.getenv('SUPABASE_JWT_SECRET')
SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_KEY = os.environ.get('SUPABASE_KEY')
SUPABASE_SERVICE_ROLE_KEY = os.environ.get('SUPABASE_SERVICE_ROLE_KEY')

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Set-Cookie']

#CSRF Configuration
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')
SAME_DOMAIN = env_to_bool('SAME_DOMAIN', False)
#CSRF_COOKIE_SAMESITE = None if _samesite_env_val.lower() == 'none' else _samesite_env_val
SECURE_SSL_REDIRECT = env_to_bool('SECURE_SSL_REDIRECT', False)
#CSRF_COOKIE_SECURE = env_to_bool('CSRF_COOKIE_SECURE', False)
#CSRF_COOKIE_NAME = os.environ.get('CSRF_COOKIE_NAME', 'csrftoken')
SESSION_COOKIE_SECURE = env_to_bool('SESSION_COOKIE_SECURE', False)
SESSION_COOKIE_SAMESITE = env_to_bool('SESSION_COOKIE_SAMESITE', False)
#CSRF_COOKIE_HTTPONLY = env_to_bool('CSRF_COOKIE_HTTPONLY', False) # Allow the frontend to access the token

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'same-origin'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'server',
    'django_countries',    
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mmsserver.middleware.security_headers.SecurityHeadersMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
   ]
}

CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-device-fingerprint',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env_to_int('ACCESS_TOKEN_LIFETIME_MINUTES', 30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=env_to_int('REFRESH_TOKEN_LIFETIME_MINUTES', 1200)),
    'ROTATE_REFRESH_TOKENS': env_to_bool('ROTATE_REFRESH_TOKENS', True),
    'BLACKLIST_AFTER_ROTATION': env_to_bool('BLACKLIST_AFTER_ROTATION', True),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.environ.get('SECRET_KEY'), 
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    #Cookie Configuration
#    'AUTH_COOKIE_SECURE': env_to_bool('AUTH_COOKIE_SECURE', False),
#    'AUTH_COOKIE_SAMESITE': os.environ.get('AUTH_COOKIE_SAMESITE', 'Lax'),
#    'AUTH_COOKIE_PATH': '/',
#    'AUTH_COOKIE_HTTP_ONLY': env_to_bool('AUTH_COOKIE_HTTP_ONLY', True),
#    'AUTH_COOKIE_ACCESS': os.environ.get('AUTH_COOKIE_ACCESS', 'access_token'),
#    'AUTH_COOKIE_REFRESH': os.environ.get('AUTH_COOKIE_REFRESH', 'refresh_token'),
    
    #JWT Claims Configuration
#    "JTI_CLAIM": "jti",
}

ROOT_URLCONF = 'mmsserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mmsserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL: 
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
    } 
else: 
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME"),
            'USER': os.getenv("DB_USER"),
            'PASSWORD': os.getenv("DB_PASSWORD"),
            'HOST': os.getenv("DB_HOST"),
            'PORT': os.getenv("DB_PORT"),
        }
    }

RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY')

#DEFAULT_FILE_STORAGE = os.getenv('DEFAULT_FILE_STORAGE')

#AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
#AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
#AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
#AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
#AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME') # optional
#AWS_S3_ADDRESSING_STYLE = "path"  # important for Supabase compatibility


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database-backed JWT storage
AUTH_USER_MODEL = 'server.User'
JWT_STORAGE_MODEL = 'server.UserJWT'


# Email Configuration
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')          
EMAIL_PORT = os.environ.get('EMAIL_PORT')                       
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')                                 
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')   
"""
MAILJET_API_KEY = os.environ.get('MAILJET_API_KEY')
MAILJET_API_SECRET = os.environ.get('MAILJET_API_SECRET')
TEMPLATE_ID = os.environ.get('TEMPLATE_ID')

STRIPE_API_KEY = os.environ.get('STRIPE_API_KEY')
STRIPE_CUS_ID = os.environ.get('STRIPE_CUS_ID')
BILLING_CONFIG_ID = os.environ.get('BILLING_CONFIG_ID')
FRONTEND_URL = os.environ.get('FRONTEND_URL')