# Generated by Django 5.2.1 on 2025-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [

    ]
