# Generated by Django 5.2.1 on 2025-05-28 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?601\\d{9,11}$', 'Enter a valid phone number')]),
        ),
    ]
