# Generated by Django 5.2.1 on 2025-07-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_reject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ic_document',
        ),
        migrations.AddField(
            model_name='user',
            name='ic_document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
