# Generated by Django 5.2.1 on 2025-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_user_beneficiary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
    ]
