# Generated by Django 5.2.1 on 2025-07-02 11:27

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_user_reject_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ic_document',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.User.user_ic_document_upload_to, verbose_name='IC/Driving License'),
        ),
    ]
