# Generated by Django 5.2.1 on 2025-06-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_depositlock_amount_1y_locked_and_more'),
    ]

    operations = [

    ]
