# Generated by Django 5.2.1 on 2025-05-31 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_user_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verfication_status',
            new_name='verification_status',
        ),
    ]
