# Generated by Django 5.2.1 on 2025-07-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_user_ic_document_user_ic_document_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', 'request_status', 'transaction_type', 'point_type', 'user'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
