# Generated by Django 5.2.1 on 2025-07-06 04:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+?60|0)1\\d{7,11}$', 'Enter a valid mobile number')]),
        ),
        migrations.CreateModel(
            name='UserJWT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('device_fingerprint', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'device_fingerprint'], name='server_user_user_id_0c5e5f_idx'), models.Index(fields=['access_token'], name='server_user_access__fb4688_idx'), models.Index(fields=['expires_at'], name='server_user_expires_77d41d_idx')],
            },
        ),
    ]
