# Generated by Django 5.2.1 on 2025-07-06 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_user_beneficiary_phone_userjwt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('total_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
            },
        ),
    ]
