# Generated by Django 5.2.1 on 2025-06-12 14:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_transaction_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_point', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('used_point', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('balance_point', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Point',
                'verbose_name_plural': 'Admin Points',
            },
        ),
        migrations.CreateModel(
            name='OperationalProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_profit_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Manually update daily profit rate (e.g., enter 5.0 for 5.0%)', max_digits=7)),
                ('weekly_profit_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Manually update weekly profit rate (e.g., enter 5.0 for 5.0%)', max_digits=7)),
                ('current_month_profit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Manually update current month profit (e.g., enter 5.0 for 5.0%)', max_digits=7)),
                ('active_month_profit', models.IntegerField(blank=True, help_text='The month (1-12) for which profit is currently active', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('active_year_profit', models.IntegerField(blank=True, help_text='The year for which profit is currently active', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational Profit',
                'verbose_name_plural': 'Operational Profits',
            },
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.CreateModel(
            name='MonthlyFinalizedProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='The year of the finalized profit (e.g., 2024).')),
                ('month', models.IntegerField(db_index=True, help_text='The month of the finalized profit (1 for January, 12 for December).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('finalized_profit_rate', models.DecimalField(decimal_places=4, help_text='The percentage profit rate applied for this month (e.g., 5.0 for 5.0%).', max_digits=7)),
                ('finalized_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this monthly profit was recorded/finalized.')),
            ],
            options={
                'verbose_name': 'Monthly Finalized Profit',
                'verbose_name_plural': 'Monthly Finalized Profits',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
