# Generated by Django 5.2.1 on 2025-07-10 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_performance_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Performance', 'verbose_name_plural': 'Performances'},
        ),
        migrations.AddField(
            model_name='performance',
            name='month',
            field=models.IntegerField(blank=True, help_text='The month (1-12) for which profit is currently active', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='performance',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('month', 'year')},
        ),
    ]
