# Generated by Django 5.2.1 on 2025-06-13 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_transferrequest_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyfinalizedprofit',
            options={'ordering': ['-year', 'month'], 'verbose_name': 'Monthly Finalized Profit', 'verbose_name_plural': 'Monthly Finalized Profits'},
        ),
        migrations.AlterField(
            model_name='monthlyfinalizedprofit',
            name='finalized_profit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The percentage profit rate applied for this month (e.g., 5.0 for 5.0%).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='operationalprofit',
            name='current_month_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manually update current month profit (e.g., enter 5.0 for 5.0%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='operationalprofit',
            name='daily_profit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manually update daily profit rate (e.g., enter 5.0 for 5.0%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='operationalprofit',
            name='weekly_profit_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manually update weekly profit rate (e.g., enter 5.0 for 5.0%)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
    ]
