# Generated by Django 5.2.1 on 2025-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_performance_options_performance_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trader',
            field=models.BooleanField(default=False),
        ),
    ]
