# Generated by Django 5.2.1 on 2025-06-24 14:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_monthlyfinalizedprofit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', 'request_status', 'transaction_type', 'user'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True, verbose_name='Request Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_campro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_point_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit Point'), ('COMMISSION', 'Commission Point'), ('ASSET', 'Asset Point')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_point_type',
            field=models.CharField(blank=True, choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit Point'), ('COMMISSION', 'Commission Point'), ('ASSET', 'Asset Point')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CONVERT', 'Convert'), ('TRANSFER', 'Transfer'), ('DISTRIBUTION', 'Distribution'), ('AFFILIATE_BONUS', 'Affiliate Bonus'), ('INTRODUCER_BONUS', 'Introducer Bonus'), ('ASSET_PLACEMENT', 'Asset Placement'), ('ASSET_WITHDRAWAL', 'Asset Withdrawal'), ('FREE_CAMPRO_GRANT', 'Free 100 USDT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='server.wallet'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit Point'), ('COMMISSION', 'Commission Point'), ('ASSET', 'Asset Point')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_free_campro', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='server.asset'),
        ),
        migrations.CreateModel(
            name='DepositLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_6m_unlocked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('amount_1y_unlocked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_free_campro', models.BooleanField(default=False)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock_info', to='server.transaction')),
            ],
            options={
                'verbose_name': 'Deposit Lock',
                'verbose_name_plural': 'Deposit Locks',
            },
        ),
        migrations.DeleteModel(
            name='TransferRequest',
        ),
    ]
