# Generated by Django 5.2.1 on 2025-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_transaction_options_transaction_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalprofit',
            options={'ordering': ['-active_year_profit', '-active_month_profit'], 'verbose_name': 'Operational Profit', 'verbose_name_plural': 'Operational Profits'},
        ),
        migrations.AlterField(
            model_name='depositlock',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterUniqueTogether(
            name='operationalprofit',
            unique_together={('active_month_profit', 'active_year_profit')},
        ),
    ]
