# Generated by Django 5.2.1 on 2025-07-31 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalprofit',
            name='active_day_profit',
            field=models.IntegerField(blank=True, help_text='The day (1-31) for which profit is currently active', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
