# Generated by Django 5.2.1 on 2025-08-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_operationalprofit_active_day_profit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalprofit',
            options={'ordering': ['active_day_profit', '-active_year_profit', '-active_month_profit'], 'verbose_name': 'Operational Profit', 'verbose_name_plural': 'Operational Profits'},
        ),
        migrations.AlterUniqueTogether(
            name='operationalprofit',
            unique_together={('active_day_profit', 'active_month_profit', 'active_year_profit')},
        ),
    ]
