# Generated by Django 5.2.1 on 2025-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_operationalprofit_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPoint',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='affiliate_point_balance',
            new_name='commission_point_balance',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='bonus_point_balance',
            new_name='introducer_point_balance',
        ),
        migrations.AlterField(
            model_name='depositlock',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit'), ('COMMISSION', 'Commission'), ('INTRODUCER', 'Introducer'), ('ASSET', 'Asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_point_type',
            field=models.CharField(blank=True, choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit'), ('COMMISSION', 'Commission'), ('INTRODUCER', 'Introducer'), ('ASSET', 'Asset')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('CONVERT', 'Convert'), ('TRANSFER', 'Transfer'), ('DISTRIBUTION', 'Distribution'), ('commission_BONUS', 'Commission Bonus'), ('INTRODUCER_BONUS', 'Introducer Bonus'), ('ASSET_PLACEMENT', 'Asset Placement'), ('ASSET_WITHDRAWAL', 'Asset Withdrawal'), ('FREE_CAMPRO_GRANT', 'Welcome Bonus'), ('MIGRATION', 'Migration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit'), ('COMMISSION', 'Commission'), ('INTRODUCER', 'Introducer'), ('ASSET', 'Asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
    ]
