# Generated by Django 5.2.1 on 2025-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_rename_commission_point_balance_wallet_affiliate_point_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', 'referred_by', 'verification_status'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='depositlock',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit'), ('COMMISSION', 'Commission'), ('ASSET', 'Asset')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('CONVERT', 'Convert'), ('TRANSFER', 'Transfer'), ('DISTRIBUTION', 'Distribution'), ('AFFILIATE_BONUS', 'Affiliate Bonus'), ('INTRODUCER_BONUS', 'Introducer Bonus'), ('ASSET_PLACEMENT', 'Asset Placement'), ('ASSET_WITHDRAWAL', 'Asset Withdrawal'), ('FREE_CAMPRO_GRANT', 'Welcome Bonus'), ('MIGRATION', 'Migration')], max_length=40),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
    ]
