# Generated by Django 5.2.1 on 2025-08-04 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_asset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to=settings.AUTH_USER_MODEL),
        ),
    ]
