# Generated by Django 5.2.1 on 2025-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_promocode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('CONVERT', 'Convert'), ('TRANSFER', 'Transfer'), ('DISTRIBUTION', 'Distribution'), ('AFFILIATE_BONUS', 'Affiliate Bonus'), ('INTRODUCER_BONUS', 'Introducer Bonus'), ('ASSET_PLACEMENT', 'Asset Placement'), ('ASSET_WITHDRAWAL', 'Asset Withdrawal'), ('WELCOME_BONUS', 'Welcome Bonus'), ('SHARING_PROFIT', 'Sharing Profit'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('MIGRATION', 'Migration')], max_length=40),
        ),
    ]
