# Generated by Django 5.2.1 on 2026-01-05 08:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositlock',
            name='freeze_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
