# Generated by Django 5.2.1 on 2026-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_depositlock_freeze_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date for the withdrawal window.', unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if the withdrawal window is active for this date.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this withdrawal window.')),
            ],
        ),
    ]
