# Generated by Django 5.2.1 on 2025-06-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_depositlock_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at', 'referred_by', 'verification_status'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='depositlock',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Request Status'),
        ),
    ]
