# Generated by Django 5.2.1 on 2026-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_withdrawalwindow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='point_type',
            field=models.CharField(choices=[('MASTER', 'Master Point'), ('PROFIT', 'Profit'), ('COMMISSION', 'Commission'), ('ASSET', 'Asset')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('CONVERT', 'Convert'), ('TRANSFER', 'Transfer'), ('DISTRIBUTION', 'Distribution'), ('AFFILIATE_BONUS', 'Affiliate Bonus'), ('INTRODUCER_BONUS', 'Introducer Bonus'), ('ASSET_PLACEMENT', 'Asset Placement'), ('ASSET_WITHDRAWAL', 'Asset Withdrawal'), ('WELCOME_BONUS', 'Welcome Bonus'), ('SHARING_PROFIT', 'Sharing Profit'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('EXPIRATION', 'Expiration'), ('MIGRATION', 'Migration')], db_index=True, max_length=40),
        ),
    ]
