# Generated by Django 5.2.1 on 2025-06-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_user_options_alter_depositlock_request_status_and_more'),
        ('server', '0017_alter_user_options_alter_depositlock_request_status_and_more'),
    ]

    operations = [
    ]
