# Generated by Django 5.2.1 on 2026-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_transaction_point_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, max_length=40, null=True, verbose_name='Request Status'),
        ),
    ]
